### ISSUE TITLE
Some exported values are not making it accross module boundaries

### ISSUE THREAD

**Issue by barrycarr** [Microsoft/vscode-debugadapter-node#10]
Hi, 
I've notice when debugging my Typescript with vscode some complex/compounds objects that are being exported from one module are either: not the same object that "arrives"  in the importer, or its fields are being reset back to their defualt values. 

I'm exporting the value, like so:
```typescript
export const target = (() => getMergedConfig().target)();
```
and importing it like this:
```typescript
import {target} from './../lib/ts-config-loader';
```
However, in the module that is receiving target, the debugger can't see `target`. I can't create a watch value and I can't query it in the console. When I access fields from target, they are usually at their defualt values. 

If I use node-debug and chrome debugger, everything works as expect and the code also runs correctly.

**Comment by weinand** [comment]
@barrycarr In your last sentence you said "If I use node-debug and chrome debugger, everything works as expect and the code also runs correctly." This confuses me because in the first sentence you said "debugging my Typescript with vscode".
Typescript debugging in VS Code is using 'node-debug'! How can this have a problem and work fine at the same time?

**Comment by weinand** [comment]
no response -> closing.
