### ISSUE TITLE
setBreakPointsRequest argument for source.name is no longer defined

### ISSUE THREAD

**Issue by StephenBloomquist** [Microsoft/vscode-debugadapter-node#109]
As the subject says. The incoming `DebugProtocol.SetBreakpointsArguments` is now giving me an undefined source name. The path remains unaffected.

This might be related to VSCode 1.11.1 as I only _just_ started experiencing this problem with no change on my end.

**Comment by Gama11** [comment]
We're having the same issue in vshaxe-debugadapter (https://github.com/vshaxe/vshaxe-debugadapter/issues/12), where setting breakpoints is broken with VSCode 1.11.x, but still works fine in 1.10.x, because the adapter assumes `arguments.source.name` to be present. The issue can still be reproduced in the latest Insider's build (Microsoft/vscode@9530cf6e2b).

**Comment by Gama11** [comment]
This seems like a bug - despite `name` being optional in `Source`, it's specified to always be included in messages sent by the debug adapter:

>**Every source returned from the debug adapter has a name.** When sending a source to the debug adapter this name is optional.

(https://github.com/Microsoft/vscode-debugadapter-node/blob/438678c7e2e4267b1df18b98234162d4fa450c8e/protocol/src/debugProtocol.ts#L1087-L1088)

**Comment by weinand** [comment]
Since this is an issue of VS Code not providing an expected value, I'll move this bug to VS Code.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode#24895
