### ISSUE TITLE
Question: Promise.all or chained?

### ISSUE THREAD

**Issue by raix** [Microsoft/vscode-debugadapter-node#115]
Should this run in sequence or does dc handle this for us?

```js
test('should stop on entry', () => {
    return Promise.all([
        dc.configurationSequence(),
        dc.launch({ program: "main.js", stopOnEntry: true }),
        dc.assertStoppedLocation('entry', 1)
    ]);
});
```

or

```js
test('should stop on entry', () => {
    return Promise.resolve()
        then(() => dc.configurationSequence())
        then(() => dc.launch({ program: "main.js", stopOnEntry: true }))
        then(() => dc.assertStoppedLocation('entry', 1));
    ]);
});
```

**Comment by raix** [comment]
...or

```js
test('should stop on entry', async () => {
  await dc.configurationSequence();
  await dc.launch({ program: "main.js", stopOnEntry: true });
  await dc.assertStoppedLocation('entry', 1);
});
```

**Comment by weinand** [comment]
The use of Promise.all runs things in parallel (which is the intended behaviour). However, since `configurationSequence` waits for an 'initialized' event and `assertStoppedLocation` waits for a stopped event, `launch` is the only thing that proceeds and generates the 'initialized' event. This makes the `configurationSequence` proceed. Later an 'stopped' event arrives which makes `assertStoppedLocation` succeed.

Your strictly sequential snippets 2 and 3 would work too, but setting up event handlers in parallel better reflects the way VS Code works.

**Comment by raix** [comment]
Thanks for the answer, I ended up with a mix.
1. Setting up event listeners
2. Calling await commands
