### ISSUE TITLE
Support setExpression request in Debug Adapter protocol

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-debugadapter-node#167]
_From @changsi-an on March 12, 2018 21:35_

- VSCode Version: 1.21.0
- OS Version: Windows 10

Does this issue occur when all extensions are disabled?: Yes

We hope that the vscode debug adapter protocol can include the `setExpression` request that is described [here](https://github.com/Microsoft/VSDebugAdapterHost/wiki/Editable-'Watch'-Window-Values)

The main purpose of this request is to allow modifying a "watch" expression. Even though VS Code does not support modifying a watch expression today. Many other debugger clients who implement VS Code debug protocol involve business of modifying a watch expression. Eg. Visual Studio who can debug Node, Chrome and Edge using VS Code debug protocol.

_Copied from original issue: Microsoft/vscode#45621_

**Comment by weinand** [comment]
The description from above is misleading.

If I understand the problem correctly, the issue is not to "allow modifying a 'watch' expression". This is possible in VS Code without any specific DAP requests (so the statement from above "VS Code does not support modifying a watch expression today" is incorrect).

The issue is to support editing the **value** of a watch expression in order to store that value in a variable (obviously this only works if the watch expression denotes a variable, that is a location where a value can be stored).

So modifying the value of the expression "a[0]" is possible whereas modifying "3*4" does not work.

**Comment by andrewcrawley** [comment]
See #85 for where we initially proposed this extension, which had some discussion of the use cases.

You are correct that this is not about modifying a watch expression, but rather about assigning a new value to the result of an expression.  Both VS and VS Code allow you to add (e.g.) `a[1000].x` to their respective "Watch" windows, but VS Code treats the result of that evaluation as read-only, whereas VS supports assigning a new value to the result of the expression (unless the adapter tells us it's read-only, as would be expected in the `3*4` case).

Although `setExpression` could be used as a replacement for `setVariable`, the reverse is not true - `setExpression` allows you to express an assignment along the lines of `this.GetSomeObject().x = 12`.  FYI, the VS host still uses `setVariable` for cases where we have a container reference.

`setExpression` has been implemented as a protocol extension in the VS host, the C# protocol library, and vsdbg for over a year, and is publicly documented, so changing the names of the parameters would be a breaking change.
