### ISSUE TITLE
runInTerminalRequest selecting shell

### ISSUE THREAD

**Issue by rogalmic** [Microsoft/vscode-debugadapter-node#200]
I would like to select proper shell when my debugger extension runs program in teminal via `runInTerminalRequest(...)`.

In essence, powershell on windows has totally different quoting + checking for active shell is a big overhead, which makes it [hard](https://github.com/Microsoft/WSL/issues/3533) to do a proper solution. 
Would it be possible to add a `shell` property? 

Something similar to:
```javascipt
vscode.window.createTerminal(`Ext Terminal #${NEXT_TERM_ID++}`, '/bin/zsh');
```

**Comment by weinand** [comment]
@rogalmic a DA doesn't know what the "proper shell" is.

Please note that the implementation of `runInTerminalRequest` in the frontend is responsible for doing the right quoting. Trying to do the "right" quoting on the calling (DA) side won't work because you don't know what shell the enduser has configured.
