### ISSUE TITLE
How to remove a breakpoint from vscode UI?

### ISSUE THREAD

**Issue by Abbyyan** [microsoft/vscode-debugadapter-node#240]
When the breakpoint command can't be solved with my debuggers, I want to remove it from vscode UI(That is to say, remove the red dot on vscode editor automatically). So i try to use the [BreakpointEvent](https://github.com/microsoft/vscode-debugadapter-node/blob/b61cf04501cfe7356b695f99bc60961684f89a4f/protocol/src/debugProtocol.ts#L179-L189) with reason `removed` . But when i send a breakpoint event, it remove all the breakpoint on the vscode editor UI. How can i set the second params of `BreakpointEvent` to remove just the error one please? 
Hope for your help. Thanks a lot.

**Comment by Abbyyan** [comment]
As shown in https://github.com/microsoft/vscode/issues/8642, install [mock-debug](https://github.com/microsoft/vscode-mock-debug.git) and the function to remove a breakpoint from UI can be achieved. 
![image](https://user-images.githubusercontent.com/12140508/103205716-294df000-4935-11eb-8ea9-235553c806d3.png)
Trying to see the code now.

**Comment by weinand** [comment]
@Abbyyan two clarifications:

First a "meta" issue: this repository is for the node.js Debug Adapter Protocol **library**, and not for the VS Code implementation of the Debug Adapter Protocol. If you see errors in VS Code, then please file them against VS Code.  

Now a clarification about breakpoints:
Breakpoints are managed by VS Code independent from a debug extension. So a user can create breakpoints at **any time** and they are passed to the debug extension (debug adapter) when a debug sessions starts. Since the user has created the breakpoint on purpose, a debug extension should not remove breakpoints lightly because that will delete "user data" (which is a no-go). Deleting breakpoints is especially painful for a user if the user has added conditions or log expressions for them: they will be lost!

So what you are trying to do is "bad practice". 

I suggest that you do not try to delete breakpoints but to "fix" them. That's what VS Code debuggers (including Mock Debug) are doing: when a breakpoint is on an empty line, they try to move them to the next non-empty line. This is done by returning the "valid location" from the "setBreakpoints" request which makes VS Code show the breakpoint in the valid location while the debug session is active.  When the debug session ends VS Code will move the breakpoints back to the original location.

**Comment by Abbyyan** [comment]
> @Abbyyan two clarifications:
> 
> First a "meta" issue: this repository is for the node.js Debug Adapter Protocol **library**, and not for the VS Code implementation of the Debug Adapter Protocol. If you see errors in VS Code, then please file them against VS Code.
> 
> Now a clarification about breakpoints:
> Breakpoints are managed by VS Code independent from a debug extension. So a user can create breakpoints at **any time** and they are passed to the debug extension (debug adapter) when a debug sessions starts. Since the user has created the breakpoint on purpose, a debug extension should not remove breakpoints lightly because that will delete "user data" (which is a no-go). Deleting breakpoints is especially painful for a user if the user has added conditions or log expressions for them: they will be lost!
> 
> In addition, a debug extension does not "own" breakpoints. If a user is using more than one debugger your debug extension will see all breakpoints, even the ones meant for another debugger. So you cannot just delete breakpoints that make no sense to you. You should leave them alone.
> 
> So what you are trying to do is "bad practice".
> 
> I suggest that you do not try to delete breakpoints but to "fix" them (or ignore them if they make no sense). That's what VS Code debuggers (including Mock Debug) are doing: when a breakpoint is on an empty line, they try to move them to the next non-empty line. This is done by returning the "valid location" from the "setBreakpoints" request which makes VS Code show the breakpoint in the valid location while the debug session is active. When the debug session ends VS Code will move the breakpoints back to the original location.

Got it. Thanks a lot.
