### ISSUE TITLE
Support debugger URI path style

### ISSUE THREAD

**Issue by felixfbecker** [microsoft/vscode-debugadapter-node#3]
XDebug wants all file paths as `file://` URI. I looked at the source code and saw that there is code implemented for this, but the property `debuggerPathsAreUris` is private, by default set to `false` and has no constructor property - in opposite to `debuggerLinesAndColumnsStartAt1`.

**Comment by felixfbecker** [comment]
What's up with the Jan 2016 milestone? If you are looking for an implementation, you might want to look at my code, I just overwrote the convert functions ;)

**Comment by weinand** [comment]
@felixfbecker Before closing this feature, I'll have to write tests...  But you can try this unverified and untested feature already (and it would actually help me finishing this ;-). On your debug session call setDebuggerPathFormat('uri'). After that the convert... methods should start convert between native paths and URIs.
Please note:
- VS Code will always use native paths, not URIs.
- paths used in the launch or attach requests are not spec'ed so their format is left open to the debug adapter developer. So you cannot use the convertClientPathToDebugger and convertDebuggerPathToClient because they assume a configured client format which might be different from what you are using in your launch config.

**Comment by felixfbecker** [comment]
I will probably keep my overwritten methods because I also resolve `localSourceRoot` with `serverSourceRoot` in there, but I'm pretty sure [your implementation](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/adapter/src/debugSession.ts#L552) of `uri2path` is not enough.
 - You must call `decodeURI` on it to handle paths with spaces or special characters
 - Windows paths will have a trailing slash in the URI (at least when they come from XDebug)
   `file:///c:/users/felix` means `url.pathname` is `/c:/users/felix`, but we need 
 - You should call `path.normalize()` on the result to replace slashes with backslashes on Windows

So it must be at least
```ts
    let filePath = decodeURI(url.parse(fileUri).pathname);
    // strip the trailing slash from Windows paths (indicated by a drive letter with a colon)
    if (/^\/[a-zA-Z]:\//.test(filePath)) {
        filePath = filePath.substr(1);
    }
    // convert slashes to backslashes on Windows
    return path.normalize(filePath);
```
For the other way I simply use the [file-url](https://www.npmjs.com/package/file-url) package with `{resolve: false}`

Hope this helps :)
