### ISSUE TITLE
Debug protocol extension: support full text ranges

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode-debugadapter-node#34]
To be able to use the debug protocol in other IDEs (Visual Studio, Xamarin Studio) or VS Code in the future we should think about how the debug protocol should support compilers/runtimes that include full text ranges (start line, start column, end line, end column) in their debug info.

Suggestions: StackFrame, SourceBreakpoint and Breakpoint interfaces should add 'endLine?: number' and 'endColumn?: number'.

**Comment by daviwil** [comment]
PowerShell's debugger allows setting a breakpoint at a specific line/column (only start position) so this would be a nice addition for us.

**Comment by weinand** [comment]
@daviwil setting breakpoints at line/column position is already possible since quite some time (and node-debug uses that).

**Comment by weinand** [comment]
@gregg-miskelly @DavidKarlas what exactly is the semantics of setting a breakpoint for a range of text (multiple lines)?

**Comment by DavidKarlas** [comment]
Imo, `SourceBreakpoint`  doesn't need endLine and endColumn.

What I meant is when breakpoint is hit we need full range, but that is provided via StackFrame, sorry for confusion I made...

For `Breakpoint(Information about a Breakpoint created in setBreakpoints or setFunctionBreakpoints.)`:
This still makes sense imo since we want to make visual effect like this after breakpoint is placed(which can be adjusted a bit depending on .pdb informations)
![image](https://cloud.githubusercontent.com/assets/774791/16305957/56a2ddf6-395c-11e6-9acc-74832297436e.png)

**Comment by gregg-miskelly** [comment]
@weinand to answer your question: In VS Code, I don't think there is any value in the end line/col for `SourceBreakpoint`. In VS we have it because the language service gets to specify where exactly it wants the breakpoint set.
