### ISSUE TITLE
Debug Protocol: support for launching debuggee in VS Code terminal 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-debugadapter-node#47]

**Comment by daviwil** [comment]
Ohhhh, nice!  This might be interesting for PowerShell.

**Comment by weinand** [comment]
I've added the first 'reverse request' to the protocol. A debug adapter can now launch a runtime or debug target in VS Code's integrated terminal.

This is the `runInTerminalRequest` in the protocol:
```ts
	/** runInTerminal request; value of command field is "runInTerminal".
		With this request a debug adapter can run a command in a terminal.
	*/
	export interface RunInTerminalRequest extends Request {
		arguments: RunInTerminalRequestArguments;
	}
	/** Arguments for "runInTerminal" request. */
	export interface RunInTerminalRequestArguments {
		/** What kind of terminal to launch. */
		kind?: 'integrated' | 'external';
		/** Optional title of the terminal. */
		title?: string;
		/** Working directory of the command. */
		cwd: string;
		/** List of arguments. The first argument is the command to run. */
		args: string[];
		/** Environment key-value pairs that are added to the default environment. */
		env?: { [key: string]: string; }
	}
	/** Response to Initialize request. */
	export interface RunInTerminalResponse extends Response {
		body: {
			/** The process ID */
			processId?: number;
		};
	}
```

The debug adapter should only use the `runInTerminalRequest` if the attribute `supportsRunInTerminalRequest` is true in the `initializeRequest`:  
```ts
		/** Client supports the runInTerminal request. */
		supportsRunInTerminalRequest?: boolean;
```

**Comment by daviwil** [comment]
This is really interesting, might have an application for the long-running debug session idea we talked about some time ago.  Scenario:

1. PowerShell extension uses the new debug launcher API to launch the long-running debug configuration
2. My TypeScript-based debug adapter code immediately sends the RunInTerminalRequest so that my language/debug server process gets launched in the integrated terminal
3. The PowerShell extension connects to the language server running in that application
4. User now has a fully integrated development/debugging session and can run debug commands, etc directly through the integrated terminal using the native PowerShell console host

What do you think?

One question: if we did manage to start this long-running debug session, is there any way we could get a flag to make the status bar not be orange all the time?  I know that sort of breaks the original UX of running in the debugger, but I think it might be a little annoying to the user if it looks like they're perpetually in the debug state.

/cc @rkeithhill
