### ISSUE TITLE
Displaying an error message immediately at startup?

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode-debugadapter-node#57]
Hey guys,

Is there a way to return a message to the user at debug adapter startup so that they don't just see "Debug adapter has terminated unexpectedly"?  There's a case where my debug adapter can't be started yet because my service hasn't finished initializing and I want to show a helpful message that makes it clear why debugging couldn't start.

I tried returning an ErrorResponse to message id 0 but it didn't show up in the UI.  Is there another message I can use for that?

Thanks!

**Comment by weinand** [comment]
@daviwil so this error message cannot come from the debug adapter because the adapter cannot be started, correct?
I think the most flexible solution is to let the extension launch the debug adapter through code and post an error notification if necessary.
The feature request for this is https://github.com/Microsoft/vscode/issues/8645

**Comment by daviwil** [comment]
Sounds good to me, thanks!
