### ISSUE TITLE
Debug Protocol: Support sending custom properties to a debug adapter while debugging

### ISSUE THREAD

**Issue by andrewcrawley** [Microsoft/vscode-debugadapter-node#62]
We propose adding a mechanism for passing simple untyped properties to a debug adapter, which can take action or not depending on its understanding of those properties.  Unlike values specified in launch.json, these properties can be changed during a debugging session based on UI actions.

Examples of properties:
- "EnableJMC" - indicate whether Just My Code should be turned on, which might (e.g.) prevent the debugger from showing framework code on the call stack
- "Radix" - indicate the number base for evaluated values returned by the debugger (e.g.) "10" or "16"

Proposed protocol changes:

```typescript
export interface Capabilities {
    // ...
    /** The debug adapter supports the setDebuggerProperty request */
    supportsSetDebuggerPropertyRequest?: boolean;
    // ...
}

/** SetDebuggerProperty request; value of command field is 'setDebuggerProperty'.  The request sets a debugger-specific property. */
export interface SetDebuggerPropertyRequest extends Request {
    arguments: SetDebuggerPropertyArguments;
}

/** Arguments for 'setDebuggerProperty' request. */
export interface SetDebuggerPropertyArguments {
    /** Name of the property to set */
    name: string;
    /** Value to which the property should be set */
    value?: string;
}

/** Response to 'setDebuggerProperty' request.  This is just an acknowledgement, so no body field is required. */
export interface SetDebuggerPropertyResponse extends Response {
}
```

@jacdavis @gregg-miskelly @richardstanton @tzwlai

**Comment by jacdavis** [comment]
If we were to add this, I would recommend SetDebuggerPropertyRequest  taking an array of name/value pairs so these can set in a single round trip.

**Comment by andrewcrawley** [comment]
We'll verify this proposal against our scenarios and send a PR.

**Comment by weinand** [comment]
Since this request is very generic it only makes sense between a frontend UI and a debug adapter that have agreed upon the name and semantics of the properties, I do not see much value of adding this to the protocol. Why and how would a random debug adapter from the Marketplace implement this request without knowing the semantics?

I suggest that those frontends that have a need for this and know that the corresponding backends can implement this, use additional 'private' requests like the one proposed here.

And it is always possible to promote a private request into the protocol spec should the need arise.

**Comment by andrewcrawley** [comment]
It would be possible to define a set of "well known" properties to control such things as stack trace formatting, decimal-vs-hex, etc, but I'm OK with having this be a private extension if you are.

**Comment by weinand** [comment]
So let's start by using a private request first and turning that into a official request later.
