### ISSUE TITLE
Debug Protocol: Extend modules support

### ISSUE THREAD

**Issue by andrewcrawley** [Microsoft/vscode-debugadapter-node#67]
We propose several changes to the modules API for better integration with VS scenarios:

- We need to be able to determine if a debug adapter supports the modules API
- We need to be able to retrieve the set of ColumnDescriptors a debug adapter uses
- We need to be able to determine the module that contains a stack frame
- Module identifiers should be ints, like other IDs in the protocol, rather than also allowing strings
- We need to express the datatype of a column so values can be parsed by UI

Proposed protocol changes:

```typescript
export interface Capabilities {
    // ...
    /** The debug adapter supports the modules request. */
    supportsModulesRequest?: boolean;
    /** The set of additional module information exposed by the debug adapter. */
    additionalModuleColumns?: ColumnDescriptor[];
    // ...
}

export interface StackFrame {
    // ...
    /** The module associated with the frame, if any. */
    moduleId?: number;
    // ...
}

export interface Module {
    // ...
    /** Unique identifier for the module. */
    id: number;
    // ...
}

export interface ColumnDescriptor {
    // ...
    // Remove member "format"
    /** Type of value contained in this column */
    type: 'string' | 'number' | 'boolean' | 'unixTimestampUTC';
    // ...
}

```

**Comment by andrewcrawley** [comment]
Whoops, forgot the name-drops: @jacdavis @gregg-miskelly @richardstanton @tzwlai

**Comment by gregg-miskelly** [comment]
We might want to have 'moduleId' be a string rather than a number for added flexibility. Otherwise LGTM.

**Comment by andrewcrawley** [comment]
Do you have a specific case in mind where strings would be better?  I went with ints because they're used everywhere else we need an id - stack frames, variable references, breakpoints, etc

**Comment by gregg-miskelly** [comment]
For concord, each module naturally has a GUID Id. So it would allow us to use that ID without needing to build yet-another-map to use integers. Certainly not the end of the world, but might be nice.

**Comment by andrewcrawley** [comment]
We'll verify this proposal against our scenarios and send a PR.

**Comment by weinand** [comment]
@andrewcrawley here is some feedback/questions:
- Capabilities: both capabilities make sense
- StackFrame.moduleId: shouldn't the `moduleId` live on the `Source` type?
- Module.id: limiting the type to `number` would be fine by me (but allowing number and strings for IDs is a frequent request that makes it easier to use GUIDs directly). 
- ColumnDescriptor.type: I don't like the 'type' (and the associated semantics) because it would be the first occurrence of this concept in the whole protocol. Typically the debug protocol sends strings and the UI just renderers them without further interpretation. So a time/date would be formatted in a debug adapter and the VS Code UI could just render it as a string without knowing that the type is "unixTimestampUTC". If special alignment is required (e.g. numbers are right aligned in a table column), the `format` attribute would provide a mechanism to communicate this to the front-end. So I suggest that we keep the `format` attribute for now and that we experiment with a value set for it.

**Comment by andrewcrawley** [comment]
I associated the module with a stack frame rather than a file because a single source file can be included in multiple modules.

I'm OK with leaving the module id as-is.  I suggested the change because this is currently the only place in the protocol where a property has multiple allowed types, so in my C# protocol implementation, I have to make it an "object", which is kind of ugly.

My problem with "everything's a string and the UI doesn't interpret anything" is that VS does need to interpret values.  For instance, when populating VS's Modules window, the module timestamp needs to be expressed as a FILETIME struct.  Dates are extra-tricky, which is why I suggested a "unixTimestampUTC" type - parsing an arbitrary string in an unknown locale into a valid date and time is basically impossible, and even setting aside the issue of interpretation, strings representing dates can't be sorted in any reasonable fashion (for instance, US-style MM/DD/YYYY dates would end up ordered by month).

I'm OK with leaving the "format" property to express such things as "right-justify this field".
