### ISSUE TITLE
Debugger crashes in server mode without error messages / stack on Node 5.x

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-debugadapter-node#7]
When I try to get at this by launching via "Debug adapter" (in server mode), first everything seems fine: status bar turns orange, I launch from cmd with extensionDevelopmentPath specified. When I hit F5 inside the extension development host, the debugger just ***crashes***, which means the status bar is blue again, while the debug adapter in the "extension development host" is still running. I have "break on uncaught exceptions" activated, so this should not happen under _any circumstances_. This is the debugger console output:
```
Debugger listening on port 16630
 waiting for debug protocol on port 4711
>> accepted connection from client


-> initializeRequest
{ type: 'request',
  seq: 1,
  command: 'initialize',
  arguments: { adapterID: 'php', linesStartAt1: true, pathFormat: 'path' } }


<- initializeResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 1,
  command: 'initialize',
  success: true }


-> launchRequest
{ type: 'request',
  seq: 2,
  command: 'launch',
  arguments:
   { name: 'Listen for XDebug',
     type: 'php',
     request: 'launch',
     port: 9000,
     debugServer: 4711,
     outDir: null,
     address: 'localhost',
     program: null,
     stopOnEntry: false,
     args: null,
     cwd: 'c:\\Users\\felix\\git\\github\\vscode-php-debug\\testproject',
     runtimeExecutable: null,
     runtimeArgs: null } }


<- launchResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 2,
  command: 'launch',
  success: true }
New XDebug Connection #1
```
And then it just crashes (VS Code status bar blue again).
No error, no stack trace, nothing.
I am completely unable to investigate the issue because I cannot step through my code, and I don't know where I can see what is causing this. Is there any logfile that I can look at?

**Comment by felixfbecker** [comment]
**I just found out that this only happens on my Surface, not on my PC.**

**Comment by felixfbecker** [comment]
Gonna close this as I cannot reproduce it myself. Sorry for the inconvenience.

**Comment by felixfbecker** [comment]
I'm sorry, it now happens on my PC aswell. I didn't even change anything, I checked out my released version. It's completely random. The bad news is that I'm now out of develop machines and can't hack on my adapter anymore.

My suspection is that this is some bug in the "server mode" of vscode-debugadapter-node, which would explain why it crashes without a stack trace / breaking on exception. **Just launching the extension without server mode works perfectly fine**.

I updated the issue description to focus on the actual issue.

**Comment by weinand** [comment]
@felixfbecker since the debug UI does not run in the extension host and is not extensible, there is no need to run the php debug extension in extension mode. Doing so makes the whole setup just more complex without any benefit. There is no code in your php debug extension that you can debug. All your code lives in the debug adapter which is a separate process.

What you should do:

Just follow the "Development Setup" section in https://code.visualstudio.com/docs/extensions/example-debuggers. Use two VSCode windows: one with your debug adapter project, one with the php test project. Run the debug adapter in server mode (so it will continue to run all the time). Add a "debugServer": 4711 to the launch config of the php test project and launch the php debug session. Now you can easily debug your debug adapter. If you make a change to the debug adapters code, just restart the debug adapter after the transpile has finished.

**Comment by felixfbecker** [comment]
@weinand I use `--extensionDevelopmentPath` because otherwise VS Code will not accept `type: "php"` in launch.json and will not know what to run when a debug session is started, so I think it is needed. 

Nevertheless, it worked perfectly before. I start the debug adapter in server mode, open the testproject from the command line with `code .\testproject `--extensionDevelopmentPath=$pwd` and start a debug session. I get "Listening on port 4711 / Connection accepted from client" in the _first Code instance _ and the logs I pasted above for InitializedRequest, LaunchRequest. Everything fine so far. Then, the second I actually get a connection from XDebug (triggered by a request to the webserver), the server mode in the _first Code instance_ will just crash, status bar turns blue again, without any errors or logs or stacktraces or whatever.

I have no idea what's causing this. It first happened on my Surface and now it is happening on my PC aswell. I can't debug anything. When I test the debug adapter without server mode it is working finde, but I am unable to debug it. I have issues at my repo and cant fix them because I cannot debug anything anymore.

**Comment by weinand** [comment]
@felixfbecker in order to make VSCode recognise the "php" type just install your php debug adapter from the marketplace. If you have the "debugServer": 4711 in your launch config, VSCode will still use the package.json from the installed extension but will not launch the debug adapter from there but instead connect to the local port 4711.

**Comment by felixfbecker** [comment]
@weinand Sure, but that limits me to the last released version on the marketplace. For example, when I implement a new setting in launch.json, VS Code will still have the old schema from the marketplace. Or if I rename a file. Thats why I prefer to get the latest version. But even when I do it like you suggest, the issue still persists.

**Comment by weinand** [comment]
@felixfbecker I just tried your setup. From the command I started VSCode 0.10.6:
`
/Users/weinand/Desktop/vscode-versions/Visual\ Studio\ Code.app/Contents/MacOS/Electron /Users/weinand/MS/Projects/vscode-php-debug/testproject --extensionDevelopmentPath=/Users/weinand/MS/Projects/vscode-php-debug
`
Then I launched another VS Code window from the command line for the php-debug-adapter project:
`
/Users/weinand/Desktop/vscode-versions/Visual\ Studio\ Code.app/Contents/MacOS/Electron /Users/weinand/MS/Projects/vscode-php-debug
`
In that window I started the "Debug adapter" launch config.
In the first VSCode I enabled the line with "debugServer":4711 and started the "Listen for XDebug" launch config. 

I immediately hit a breakpoint in the launchRequest and when setting a breakpoint in a php file I hit the setBreakpointsRequest. Since I don't have php and XDebug installed I could not go further.

@felixfbecker are you able to get this far?

**Comment by felixfbecker** [comment]
@weinand Thank you a lot for looking into this!

------------------------

When I don't set any breakpoint, everything works fine:

-------------------------
![without_breakpoint](https://cloud.githubusercontent.com/assets/10532611/12249992/eb8f7010-b8c3-11e5-9b59-c19f94a4ae6e.gif)

---------------------------------------

But when as I set a breakpoint like you did in the beginning `launchRequest`, the adapter hangs and the breakopoint is never reached:

----------------------

![with_breakpoint](https://cloud.githubusercontent.com/assets/10532611/12249997/034faba2-b8c4-11e5-964f-3636f4e8f2e9.gif)

----------------------
Again, the _only_ difference is the presence of a breakpoint. There is an incoming `launchRequest`, but it gets never answered.

**Comment by felixfbecker** [comment]
@weinand I investigated further and pinpointed the exact location after which the adapter hangs (sourcemaps disabled for extra clarity):

![weird](https://cloud.githubusercontent.com/assets/10532611/12250361/9c9647ce-b8c6-11e5-8161-484948904991.gif)

Please note that I only did a step over, so it should have stopped at line 189. Instead, it hung.

weirdly, setting a breakpoint here makes it hang already after logging the `InitializedRequest`. In the previous example with a breakpoint in `launchRequest` it hung after logging the `launchRequest`.

`dispatchRequest` of vscode-debugadapter-node's DebugSession class is never reached when I set a breakpoint in there.

**Comment by felixfbecker** [comment]
Are there any communication logs between VS Code and the _Node_ debug adapter (which seems to fail here) I can look at?

**Comment by weinand** [comment]
@felixfbecker since it fails for you on Windows, I will try my experiment on Windows too.
BTW, what version of node are you using? If you are using a 5.x version, could you please try a 4.1.x version. Thanks!

**Comment by felixfbecker** [comment]
@weinand I'm on 5.4.1

**Comment by felixfbecker** [comment]
I just tried to install 4.1.1 and it is now working again!!!
I wasn't aware that this would have any impact - the question is this because of the mismatch of versions between Electron and the adapter or is it simply some breaking change in 5.x that broke vscode-debugadapter? In that case, there should be an engine field added to package.json

**Comment by weinand** [comment]
@felixfbecker yes, node 5.x is showing some issues with VS Code debugging (e.g. https://github.com/Microsoft/vscode/issues/1384). For now I suggest to always stay on the node version that VS Code uses because that's the version we've verified.

**Comment by weinand** [comment]
closing
