### ISSUE TITLE
How to get notified when the runInTerminal script exited?

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-debugadapter-node#70]
I previously did this when a program was run in terminal:
```ts
script.on('exit', () => {
   this.sendEvent(new vscode.TerminatedEvent());
});
```

How can I accomplish this with `runInTerminal` request?

**Comment by roblourens** [comment]
There is no way - vscode is just sending the command at the terminal as text, and doesn't know anything about the process it spawns. The node adapters query for the process ID, and poll for it to be not running anymore, (and also listen for the debug socket to be closed).

**Comment by felixfbecker** [comment]
Thanks for the clarification. I think I also found a workaround

**Comment by felixfbecker** [comment]
Okay, the workaround I used relied on the debugger reporting when the script exits, which doesn't work with `noDebug`. If VS Code just sends the command as text, how does VS Code know the processId?

**Comment by roblourens** [comment]
It doesn't

**Comment by gregg-miskelly** [comment]
@felixfbecker we haven't tried this yet with the VS Code terminal for the C# and C++ extension, but we solved a very similar problem for spawning external terminal. We made this work by running a bash script which would spawn the debuggee but also write to fifo's to tell our extension what was happening (ex: debuggee's pid, when it exited etc). Here is the code in case it proves useful:

https://github.com/Microsoft/MIEngine/blob/master/src/MICore/Transports/LocalUnixTerminalTransport.cs

**Comment by felixfbecker** [comment]
@gregg-miskelly vscode-php-debug already had support for launching an external terminal through a helper script, but I wanted to implement the runInTerminal request to support the internal terminal

**Comment by gregg-miskelly** [comment]
Yes, I understand. My suggestion (and again I haven't actually tried this, so maybe this will not work) is that instead of sending `myProgram myArgs` to the VS Code terminal instead send `~/vscode/extensions/.../run-target-process.sh 6b978b1f4e3041d4991612a809709cb0 myProgram myArgs` so that run-target-process.sh can spawn `myProgram` and communicate back to your extension its pid, tell you when it exited, etc (using the GUID to indicate the name of the pipes you can use to communicate between the two processes).

**Comment by felixfbecker** [comment]
Pfffff sounds complicated 😅 I guess users will have to live without `TerminatedEvent`s for now if they use internal console 😄
