### ISSUE TITLE
A question about requests and responses

### ISSUE THREAD

**Issue by StephenBloomquist** [Microsoft/vscode-debugadapter-node#98]
I apologize if this has been answered elsewhere, I can't seem to find any _definitive_ answer, only things that lead me to think that I might be alright.

Is a call to `sendResponse` _required_ for every request, or is it safe to take a request and handle it in a way that doesn't send a response?

Example: I would like to assume full control over when the VSCode debugger UI changes its state between paused and running, so I don't want it changing states when `continueRequest` responds, and would rather it change later when I send a `ContinuedEvent`. Am I safe to simply omit the response, or can I not do that?

Thanks in advanced for your help!

**Comment by weinand** [comment]
@StephenBloomquist every request needs a response. Otherwise the requesting side will run into an timeout error (which is treated as failure of the request).

- **stopped -> running transition**: Since the 'continue' event is optional (and most debuggers do not send it), the VS Code frontend assumes that after a 'continue', 'next', or 'stepIn/Out' request the state of the debuggee is 'running'.
- **running -> stopped transition**: the VS Code frontend needs a 'stopped' event for this.

@isidorn please correct me if my summary is wrong.

**Comment by isidorn** [comment]
@weinand exactly right. The ordering is quite important here so vscode does not end up in a wrong state.

**Comment by StephenBloomquist** [comment]
Hey, thanks for the reply!

I'm working with hooking VSCode to a Duktape debugger. The issue I'm having to try and solve here is that the continue request has to cross a socket boundary (meaning I have to work with this asynchronously) and on occasionally duktape can execute and hit a breakpoint so fast that it sends a notification that it had paused before `continueRequest` can confirm that the request was processed and respond to the session, which can end up causing a situation with the session being told to stop too early and thus locking up the UI.

The debugger @harold-b is working on currently gets around this by assuming the request to duktape will be successful and responding to VSCode immediately without waiting to hear if the request was in fact processed.

This is the execution order I currently have working for my debugger:
1. `continueRequest` is called
2. A request to resume is sent to duktape and `continueRequest` returns shortly after without sending any response.
3. Duktape confirms the reply (which goes unheard) and continues which results in a status notification saying that duktape has entered a running state.
4. The notification is processed and, in this case, sends a ContinuedEvent to the session.
5. Duktape eventually encounters some reason to pause and sends a status notification saying it has entered a paused state.
6. The notification is processed and sends a StoppedEvent to the session.

It sounds like you're saying not responding at all will be treated similarly to responding with `response.success = false` ... It would be nice if there were a way for me to simply inform the session that its request will be handled externally and that its request was neither a success nor a failure.

**Comment by weinand** [comment]
The approach that  @harold-b is using, is what we recommend (and do ourselves).

Alternative:

If Duktape is actually always sending a "ContinuedEvent", you could use that event in the debug adapter to send back the OK response for the continueRequest (and a failure response in case no  "ContinuedEvent" arrives from Duktape in a reasonable amount of time).

The only requirement for this to work is that the Duktape PauseEvent comes always **after** the Duktape ContinuedEvent (which is probably the case because otherwise the causality would be reversed).




You do not have to send response for the continueRequest

**Comment by StephenBloomquist** [comment]
Thanks! I'll try and work out a good way to do this with this new information. 

I just don't like saying the state of something changed by assuming the state change will be successful, rather than saying the state changed because it did in fact change, which is why I'm probing around for extra information.
